### ISSUE TITLE
Dynasty sub-branches not lore-friendly

### ISSUE THREAD

**Issue by ajjr1996** [JonStryker/Witcher#116]

**Comment by ajjr1996** [comment]
We should make the sub-branch of the Radovid dynasty called "Trojan" not related to their dynasty making them seperate, since it's technically not lore friendly, same with Unicorn bloodline, they also have a sub-branch that's not lore-friendly that should probably also be unrelated as well.

**Comment by rquinio** [comment]
Is it related to these cadet branches getting the bloodlines ? Maybe bastards could be excluded to these bloodlines, that would solve it.

**Comment by ajjr1996** [comment]
For sure I think that would be a good idea!

**Comment by rquinio** [comment]
ajjr1996: "Hey I wasn't sure if I should open another issue for this so I thought I'd say it here. I was also looking and I'm not sure if not allowing bastards is a good idea anymore :( it didn't really go as I thought it would with the recent tweak of making the bloodlines unable to be inherited by bastards. It's really easy for the bloodlines to die out now since Henselt's kids and Foltest's are all bastards. I was kind of thinking more so on just editing the history and possibly making those cadet dynasties unrelated so they don't start with the bloodline."
