### ISSUE TITLE
History modding changes

### ISSUE THREAD

**Issue by ajjr1996** [JonStryker/Witcher#128]
So sorry, I tried to upload a few tweaks but I messed it up royally. I'll just leave it up to you! I uploaded all the zips underneath the correlated issue. :( I apologize again for mucking things up

**Comment by rquinio** [comment]
No worries, I'm focusing on game breaking bugs first, before history changes though.
It would be very helpful and time saving for me if you could submit these changes via git pull requests instead of zip files, though I understand this can be quite complex.
If @JonStryker or someone else could review the changes that would also be great, since I'm missing some background knowledge.
