### ISSUE TITLE
Be a better christian

### ISSUE THREAD

**Issue by TerryDuke** [JonStryker/Witcher#91]
**Repro Steps**
1. Start a game and play for a while.
2. Wait until you get the random event about priests pestering you.

**Actual**
One of the options states for the event states "Oh Queen of the Fields, help me and I'll be a better Christian".

**Expected**
It is expected that there is no reference to Christian (or Muslim, etc...) in the Witcher Kings game, and that this be replaced with the appropriate devout name or something generic such as "I'll be a better devout worshiper".

**Notes**
The event is defined in EVTDESC100230:
```EVTDESC100230;The [Root.Religion.GetName] priests are constantly pestering me about religion, [Root.Religion.GetRandomGodName] and money to the church. No matter what I do, promise to pray more or read the holy scripture more thoroughly they won't leave me alone!;```

The option is defined in EVTOPTB100230:
```EVTOPTB100230;Oh [Root.Religion.GetRandomGodName], help me and I'll be a better [Root.GetReligionAdherent]!;```

GetReligionAdherent, in turn, is defined in 00_customizable_localisation.txt

![bug07-better-christian](https://user-images.githubusercontent.com/39809872/41160898-01ee61be-6aff-11e8-8ae1-cacef1cc7aa5.png)

**Comment by rquinio** [comment]
Some ideas for GetReligionAdherent:
* a good fallback could be "[This.Religion.GetName] follower" (ex: Melitele follower, Kreve follower, etc.) 
* "Eternal Fire worshipper" ?
* For druidic: "Nature worshipper" ?
* For the non-human races it's a bit special because I think their religions were invented, maybe just "Elf", "Dwarf", "Halfling", "Gnome", "Dryad" ?

**Comment by TerryDuke** [comment]
Proposed fix is in Pull Request #92
